### ISSUE TITLE
Erro em `request/list`

### ISSUE THREAD

**Issue by henriquekato** [mocno/server-josmar#18]
Erro ao colocar `date_end` como parâmetro:

<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '` &lt; '2022-10-12 12:59:00' and '2022-10-12 12:59:00' &lt; `date_expected_end` and '2' at line 1 in /var/www/html/api/library/database.class.php:67
Stack trace:
#0 /var/www/html/api/library/database.class.php(67): PDOStatement-&gt;execute(Array)
#1 /var/www/html/api/request/list.php(63): ColumnDB::search('WHERE `user` IN...', Array, Array)
#2 {main}
  thrown in <b>/var/www/html/api/library/database.class.php</b> on line <b>67</b><br />

**Comment by henriquekato** [comment]
E se o `parâmetro de data` for igual a `date_expected` de algum `request já criado`: `list` retorna false

parâmetro
`"date_start= 2022-10-10 12:00:00"`

request já criado
`"date_expected_start": "2022-10-10 12:00:00"`

json
`"list": false`

**Comment by mocno** [comment]
> Erro ao colocar `date_end` como parâmetro:
> 
> 
> Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '` < '2022-10-12 12:59:00' and '2022-10-12 12:59:00' < `date_expected_end` and '2' at line 1 in /var/www/html/api/library/database.class.php:67 Stack trace: #0 /var/www/html/api/library/database.class.php(67): PDOStatement->execute(Array) #1 /var/www/html/api/request/list.php(63): ColumnDB::search('WHERE `user` IN...', Array, Array) #2 {main} thrown in /var/www/html/api/library/database.class.php on line 67

Esse erro foi causado um simples \` que faltava no código :neutral_face:

**Comment by mocno** [comment]
> E se o `parâmetro de data` for igual a `date_expected` de algum `request já criado`: `list` retorna false
> 
> parâmetro `"date_start= 2022-10-10 12:00:00"`
> 
> request já criado `"date_expected_start": "2022-10-10 12:00:00"`
> 
> json `"list": false`

E para arrumar esse problema foi necessário refazer a pesquisa por data, espero que isso não atrapalhe no aplicativo.

Agora, quando é dado o `request_date_start` e o `request_date_end`, a pagina retorna todos os pedidos com interferência de horários, a ideia era facilitar para o aplicativo.

**Comment by mocno** [comment]
tinha esquecido desse erro, por isso demorei
