### ISSUE TITLE
Erros em `api/request/create`

### ISSUE THREAD

**Issue by henriquekato** [mocno/server-josmar#22]
- [x] se um pedido for `canceled` / `ended` (antes do fim) não é possível (re)agendar a chave no horário desse pedido (`canceled` / `ended`)
      "key": 2,
      "status": 6,
      "date_expected_start": "2022-10-15 12:00:00",
      "date_expected_end": "2022-10-15 14:00:00"
- [x] é possível agendar a chave q já está `started` (no mesmo horário)
"id": 4,
"key": 2,
"status": 3,
"date_expected_start": "2022-10-11 12:00:00",
"date_expected_end": "2022-10-11 14:00:00"

     "id": 5,
"key": 2,
"status": 1,
"date_expected_start": "2022-10-11 12:00:00",
"date_expected_end": "2022-10-11 14:00:00"
- [x] não é possível agendar um pedido se o `date_start` for igual ao `date_end` de outro pedido já criado (e `date_end` novo igual ao `date_start` já criado)

**Comment by mocno** [comment]
Supostamente todos esses erros foram arrumados, mas vou deixar esse issue aberto para que quando você puder testar e verificar se está tudo certo fecha-lo.

**Comment by mocno** [comment]
o terceiro erro foi arrumado com a mesma verificação do `api/request/list`, então se houver algo errado em um os dois vão estar errados.
